import type { Metadata } from 'next';
import { SITE, toolBySlug } from '@/lib/site';
import { UuidGenerator } from '@/components/Generators';

const tool = toolBySlug('uuid-generator')!;

export const metadata: Metadata = {
  title: tool.title,
  description: tool.description,
  alternates: { canonical: `${SITE.url}/uuid-generator` },
  openGraph: { title: tool.title, description: tool.description, url: `${SITE.url}/uuid-generator` },
};

const FAQ = [
  {
    "q": "Are these safe to use as database keys?",
    "a": "Yes."
  },
  {
    "q": "Are they generated on a server?",
    "a": "No."
  },
  {
    "q": "Why no version 1?",
    "a": "Version 1 embeds a timestamp and the machine MAC address, which leaks information and is rarely what people actually want."
  }
];

export default function Page() {
  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{
          __html: JSON.stringify([
            {
              '@context': 'https://schema.org',
              '@type': 'SoftwareApplication',
              name: tool.name,
              applicationCategory: 'UtilitiesApplication',
              operatingSystem: 'Any, runs in a web browser',
              url: `${SITE.url}/uuid-generator`,
              description: tool.description,
              offers: { '@type': 'Offer', price: '0', priceCurrency: 'USD' },
            },
            {
              '@context': 'https://schema.org',
              '@type': 'FAQPage',
              mainEntity: FAQ.map((f) => ({
                '@type': 'Question',
                name: f.q,
                acceptedAnswer: { '@type': 'Answer', text: f.a },
              })),
            },
          ]),
        }}
      />

      <div className="mx-auto w-full max-w-6xl px-5 py-12">
        <h1 className="max-w-3xl text-3xl font-semibold tracking-tight sm:text-4xl">Generate UUIDs</h1>
        <p className="mt-3 max-w-2xl leading-relaxed text-ink-soft">Version 4 UUIDs, one or five hundred, generated by your browser.</p>

        <div className="mt-10">
          <UuidGenerator />
        </div>

        <section className="mt-20 max-w-2xl">
          <h2 className="text-xl font-semibold tracking-tight">Questions</h2>
          <dl className="mt-6 space-y-7">
            {FAQ.map((f) => (
              <div key={f.q}>
                <dt className="font-medium">{f.q}</dt>
                <dd className="mt-1.5 leading-relaxed text-ink-soft">{f.a}</dd>
              </div>
            ))}
          </dl>
        </section>
      </div>
    </>
  );
}
