/**
 * Writes STATUS.md from the tool and conversion lists.
 *
 * Generated rather than maintained, because a hand written checklist is exactly
 * the thing that goes quietly wrong: a tool ships, nobody ticks the box, and
 * later it looks unbuilt and gets built twice, or it looks done and gets
 * skipped. The lists in src/lib are the only truth and this just reads them.
 *
 * Run with: npm run status
 */

import { writeFileSync, existsSync } from 'node:fs';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { dirname, join } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, '..');

// pathToFileURL rather than a bare path: on Windows an absolute path starts
// with a drive letter, and the ESM loader reads "c:" as an unsupported protocol.
const load = (rel) => import(pathToFileURL(join(root, rel)).href);

const { TOOLS, CATEGORIES } = await load('src/lib/site.ts');
const { CONVERSIONS, canvasHandles } = await load('src/lib/conversions.ts');

const tick = (live) => (live ? 'x' : ' ');

const lines = [];
lines.push('# Build status');
lines.push('');
lines.push('Generated by `npm run status`. Do not edit by hand: it is rebuilt from');
lines.push('`src/lib/site.ts` and `src/lib/conversions.ts`, which are the only truth about');
lines.push('what exists.');
lines.push('');

const toolsDone = TOOLS.filter((t) => t.live).length;
const convDone = CONVERSIONS.filter((c) => c.live).length;
const total = TOOLS.length + CONVERSIONS.length;
const done = toolsDone + convDone;

lines.push(
  `**${done} of ${total} done.** Tools ${toolsDone}/${TOOLS.length}, conversions ${convDone}/${CONVERSIONS.length}.`,
);
lines.push('');

lines.push('## Tools');
lines.push('');
for (const category of CATEGORIES) {
  const inCat = TOOLS.filter((t) => t.category === category);
  if (!inCat.length) continue;
  lines.push(`### ${category}`);
  lines.push('');
  for (const t of inCat) {
    lines.push(`- [${tick(t.live)}] \`/${t.slug}\` — ${t.name}`);
  }
  lines.push('');
}

lines.push('## Conversions');
lines.push('');
const bySource = new Map();
for (const c of CONVERSIONS) {
  if (!bySource.has(c.from.label)) bySource.set(c.from.label, []);
  bySource.get(c.from.label).push(c);
}
for (const [source, list] of bySource) {
  const doneHere = list.filter((c) => c.live).length;
  lines.push(`### From ${source} (${doneHere}/${list.length})`);
  lines.push('');
  for (const c of list) {
    lines.push(`- [${tick(c.live)}] \`/${c.slug}\` — ${c.from.label} to ${c.to.label}`);
  }
  lines.push('');
}

writeFileSync(join(root, 'STATUS.md'), lines.join('\n'), 'utf8');
console.log(`STATUS.md written. ${done}/${total} done.`);

/*
 * Anything marked live must have a route, or it 404s.
 *
 * The catch-all at src/app/[slug] deliberately skips live entries, so marking
 * something live without writing its folder removes the coming soon page and
 * puts nothing in its place. That is how /heic-to-webp broke: the converter
 * handled WebP, the flag said live, and the URL served a 404 that nothing
 * complained about. Checked here because this is the script that already knows
 * what claims to exist.
 */
const missing = [
  ...TOOLS.filter((t) => t.live).map((t) => t.slug),
  // Canvas pairs are served by src/app/[slug], so they are live with no folder
  // of their own and are exempt from the folder check.
  ...CONVERSIONS.filter((c) => c.live && !canvasHandles(c)).map((c) => c.slug),
].filter((slug, i, all) => all.indexOf(slug) === i)
  .filter((slug) => !existsSync(join(root, 'src/app', slug, 'page.tsx')));

if (missing.length) {
  console.error(
    `\nMarked live with no route: ${missing.join(', ')}\n` +
      `Each needs src/app/<slug>/page.tsx, or it will 404.`,
  );
  process.exit(1);
}
